server:
  port: 8080

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8080/oauth2/jwks}
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8080}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        # OAuth / Auth Server
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/oauth2/**,/login,/login/**,/logout,/userinfo,/error,/default-ui.css,/favicon.ico,/.well-known/openid-configuration,/.well-known/oauth-authorization-server
          filters:
            - PreserveHostHeader

        # User
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        # 현재 Course API -> News Service
        - id: news-service
          uri: lb://news-service
          predicates:
            - Path=/api/courses/**,/api/games/**,/api/news/**,/api/topics/**

        # 현재 Enrollment API -> Interest Service
        - id: interest-service
          uri: lb://interest-service
          predicates:
            - Path=/api/enrollments/**

        # 현재 Payment API -> Collector Service
        - id: collector-service
          uri: lb://collector-service
          predicates:
            - Path=/api/payments/**

        # 현재 Recommend API -> Insight Service
        - id: insight-service
          uri: lb://insight-service
          predicates:
            - Path=/api/recommend/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.lecture.gateway.filter: DEBUG
