server:
  port: 8083

spring:
  application:
    name: interest-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3379/game_news_db}
    username: ${SPRING_DATASOURCE_USERNAME:manager}
    password: ${SPRING_DATASOURCE_PASSWORD:SqlDba-1}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true

service:
  news-service:
    url: ${NEWS_SERVICE_URL:http://news-service:8082}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false
