server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3379/game_news_db}
    username: ${SPRING_DATASOURCE_USERNAME:manager}
    password: ${SPRING_DATASOURCE_PASSWORD:SqlDba-1}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

app:
  jwt:
    private-key-base64: ${JWT_PRIVATE_KEY_BASE64}
    public-key-base64: ${JWT_PUBLIC_KEY_BASE64}
    key-id: ${JWT_KEY_ID:game-news-key-1}
    issuer: ${JWT_ISSUER:game-news}
    access-token-ttl-seconds: ${JWT_ACCESS_TOKEN_TTL_SECONDS:3600}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.gamenews.user: DEBUG
    org.springframework.web: DEBUG
