server:
  port: 8084

spring:
  application:
    name: collector-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

collector:
  sources:
    pcgamer:
      rss-url: ${PCGAMER_RSS_URL:https://www.pcgamer.com/rss/}
      enabled: ${PCGAMER_SCHEDULER_ENABLED:true}
      limit: ${PCGAMER_SCHEDULER_LIMIT:10}
      initial-delay: ${PCGAMER_SCHEDULER_INITIAL_DELAY:10000}
      fixed-delay: ${PCGAMER_SCHEDULER_FIXED_DELAY:600000}
    destructoid:
      rss-url: ${DESTRUCTOID_RSS_URL:https://www.destructoid.com/feed/}
      enabled: ${DESTRUCTOID_SCHEDULER_ENABLED:true}
      limit: ${DESTRUCTOID_SCHEDULER_LIMIT:10}
      initial-delay: ${DESTRUCTOID_SCHEDULER_INITIAL_DELAY:20000}
      fixed-delay: ${DESTRUCTOID_SCHEDULER_FIXED_DELAY:600000}
  news-service:
    base-url: ${NEWS_SERVICE_URL:http://localhost:8082}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
